package org.example.npbk.db;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class Database {
    private final String jdbcUrl;

    public Database() {
        Path dbDir = Path.of(System.getProperty("user.home"), ".npbk-prototype");
        try {
            Files.createDirectories(dbDir);
        } catch (Exception ex) {
            throw new IllegalStateException("Could not create database directory: " + dbDir, ex);
        }
        this.jdbcUrl = "jdbc:h2:file:" + dbDir.resolve("npbk").toAbsolutePath() + ";AUTO_SERVER=TRUE";
    }

    public Database(String jdbcUrl) {
        this.jdbcUrl = jdbcUrl;
    }

    public Connection getConnection() throws SQLException {
        return DriverManager.getConnection(jdbcUrl, "sa", "");
    }

    public void initialize() throws SQLException {
        try (Connection conn = getConnection(); Statement st = conn.createStatement()) {
            st.execute("""
                CREATE TABLE IF NOT EXISTS lookup_values (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    lookup_type VARCHAR(80) NOT NULL,
                    display_name VARCHAR(255) NOT NULL,
                    active BOOLEAN NOT NULL DEFAULT TRUE,
                    sort_order INT NOT NULL DEFAULT 0,
                    UNIQUE(lookup_type, display_name)
                )
                """);

            st.execute("""
                CREATE TABLE IF NOT EXISTS summary_settings (
                    id BIGINT PRIMARY KEY,
                    organization_name VARCHAR(255) NOT NULL DEFAULT '',
                    branch_name VARCHAR(255) NOT NULL DEFAULT '',
                    kingdom_name VARCHAR(255) NOT NULL DEFAULT '',
                    period_start DATE,
                    period_end DATE,
                    prepared_by VARCHAR(255) NOT NULL DEFAULT '',
                    notes CLOB,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
            st.execute("""
                CREATE TABLE IF NOT EXISTS budget_lines (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    fund VARCHAR(255) NOT NULL DEFAULT '',
                    budget_category VARCHAR(255) NOT NULL DEFAULT '',
                    line_type VARCHAR(30) NOT NULL DEFAULT 'EXPENSE',
                    planned_amount DECIMAL(19,2) NOT NULL DEFAULT 0,
                    actual_amount DECIMAL(19,2) NOT NULL DEFAULT 0,
                    variance_amount DECIMAL(19,2) NOT NULL DEFAULT 0,
                    notes CLOB,
                    validation_state VARCHAR(20) NOT NULL DEFAULT 'OK',
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
            st.execute("""
                CREATE TABLE IF NOT EXISTS outstanding_items (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    source_transaction_id BIGINT,
                    date_issued DATE,
                    reference_number VARCHAR(100),
                    name VARCHAR(255),
                    details CLOB,
                    bank_account VARCHAR(255),
                    direction VARCHAR(30) NOT NULL DEFAULT 'OUTGOING',
                    amount DECIMAL(19,2) NOT NULL DEFAULT 0,
                    cleared_date DATE,
                    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
                    notes CLOB,
                    validation_state VARCHAR(20) NOT NULL DEFAULT 'OK',
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
            st.execute("""
                CREATE TABLE IF NOT EXISTS supplemental_lines (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    linked_transaction_id BIGINT,
                    line_kind VARCHAR(40) NOT NULL,
                    counterparty VARCHAR(255),
                    description CLOB,
                    reference VARCHAR(100),
                    amount DECIMAL(19,2) NOT NULL DEFAULT 0,
                    due_date DATE,
                    start_date DATE,
                    end_date DATE,
                    remaining_amount DECIMAL(19,2) NOT NULL DEFAULT 0,
                    notes CLOB,
                    validation_state VARCHAR(20) NOT NULL DEFAULT 'OK',
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
            st.execute("""
                CREATE TABLE IF NOT EXISTS inventory_items (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    item_number VARCHAR(100),
                    acquired_date DATE,
                    description CLOB,
                    quantity DECIMAL(19,2) NOT NULL DEFAULT 0,
                    total_value DECIMAL(19,2) NOT NULL DEFAULT 0,
                    item_type VARCHAR(255),
                    used_for VARCHAR(255),
                    guardian_name VARCHAR(255),
                    confirmed_date DATE,
                    notes CLOB,
                    validation_state VARCHAR(20) NOT NULL DEFAULT 'OK',
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
            st.execute("""
                CREATE TABLE IF NOT EXISTS supply_items (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    description CLOB,
                    quantity DECIMAL(19,2) NOT NULL DEFAULT 0,
                    unit_cost DECIMAL(19,2) NOT NULL DEFAULT 0,
                    total_value DECIMAL(19,2) NOT NULL DEFAULT 0,
                    used_for VARCHAR(255),
                    location VARCHAR(255),
                    guardian_name VARCHAR(255),
                    notes CLOB,
                    validation_state VARCHAR(20) NOT NULL DEFAULT 'OK',
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
            st.execute("""
                CREATE TABLE IF NOT EXISTS bank_statement_lines (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    bank_account VARCHAR(255),
                    statement_date DATE,
                    posted_date DATE,
                    description CLOB,
                    amount DECIMAL(19,2) NOT NULL DEFAULT 0,
                    status VARCHAR(30) NOT NULL DEFAULT 'IMPORTED',
                    matched_transaction_id BIGINT,
                    notes CLOB,
                    validation_state VARCHAR(20) NOT NULL DEFAULT 'OK',
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
            st.execute("""
                CREATE TABLE IF NOT EXISTS period_close_records (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    period_start DATE,
                    period_end DATE,
                    bank_reconciled BOOLEAN NOT NULL DEFAULT FALSE,
                    schedules_reviewed BOOLEAN NOT NULL DEFAULT FALSE,
                    reports_generated BOOLEAN NOT NULL DEFAULT FALSE,
                    close_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
                    notes CLOB,
                    validation_state VARCHAR(20) NOT NULL DEFAULT 'OK',
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);

            st.execute("""
                CREATE TABLE IF NOT EXISTS transactions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    transaction_date DATE,
                    reference_number VARCHAR(100),
                    legal_name VARCHAR(255),
                    details CLOB,
                    bank_account VARCHAR(255),
                    affects_bank VARCHAR(30) NOT NULL,
                    budget_category VARCHAR(255),
                    affects_budget VARCHAR(30) NOT NULL,
                    fund VARCHAR(255),
                    amount DECIMAL(19,2) NOT NULL DEFAULT 0,
                    bank_effect DECIMAL(19,2) NOT NULL DEFAULT 0,
                    budget_effect DECIMAL(19,2) NOT NULL DEFAULT 0,
                    validation_state VARCHAR(20) NOT NULL DEFAULT 'OK',
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
            seedLookups(st);
        }
    }

    private void seedLookups(Statement st) throws SQLException {
        seed(st, "BANK_ACCOUNT", "Checking", 10);
        seed(st, "BANK_ACCOUNT", "Savings", 20);
        seed(st, "FUND", "General Fund", 10);
        seed(st, "FUND", "Restricted Fund", 20);
        seed(st, "BUDGET_CATEGORY", "Administrative", 10);
        seed(st, "BUDGET_CATEGORY", "Event Income", 20);
        seed(st, "BUDGET_CATEGORY", "Food", 30);
        seed(st, "BUDGET_CATEGORY", "Meeting Space", 40);
        seed(st, "BUDGET_CATEGORY", "Winter Snowball Fight 2026", 50);
        seed(st, "BUDGET_CATEGORY", "Donations", 60);
        seed(st, "BUDGET_CATEGORY", "Equipment", 70);
        seed(st, "ITEM_TYPE", "Regalia", 10);
        seed(st, "ITEM_TYPE", "Equipment", 20);
        seed(st, "ITEM_TYPE", "Supplies", 30);
    }

    private void seed(Statement st, String type, String name, int order) throws SQLException {
        st.executeUpdate("""
            MERGE INTO lookup_values (lookup_type, display_name, active, sort_order)
            KEY (lookup_type, display_name)
            VALUES ('%s', '%s', TRUE, %d)
            """.formatted(type, name.replace("'", "''"), order));
    }
}
