package org.example.npbk.db;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * H2 database bootstrap for the JavaFX prototype.
 *
 * The schema is intentionally accounting-native.  Workbook pages are treated as
 * data-entry/report views over these records, not as generic persisted cells.
 */
public class Database {
    private final String jdbcUrl;

    public Database() {
        Path dbDir = Path.of(System.getProperty("user.home"), ".npbk-prototype");
        try {
            Files.createDirectories(dbDir);
        } catch (Exception ex) {
            throw new IllegalStateException("Could not create database directory: " + dbDir, ex);
        }
        this.jdbcUrl = "jdbc:h2:file:" + dbDir.resolve("npbk").toAbsolutePath() + ";AUTO_SERVER=TRUE";
    }

    public Database(String jdbcUrl) {
        this.jdbcUrl = jdbcUrl;
    }

    public Connection getConnection() throws SQLException {
        return DriverManager.getConnection(jdbcUrl, "sa", "");
    }

    public void initialize() throws SQLException {
        try (Connection conn = getConnection(); Statement st = conn.createStatement()) {
            dropReportViews(st);
            dropLegacyPrototypeTransactionsIfNeeded(conn, st);

            createAccountingCore(st);
            createWorkbookSupportTables(st);
            createSearchIndexes(st);
            createReportViews(st);
            seedReferenceData(st);
        }
    }

    private void dropReportViews(Statement st) throws SQLException {
        st.execute("DROP VIEW IF EXISTS ledger_search");
        st.execute("DROP VIEW IF EXISTS transactions_list_view");
        st.execute("DROP VIEW IF EXISTS all_checks_tfrs_view");
        st.execute("DROP VIEW IF EXISTS fund_transfers_view");
        st.execute("DROP VIEW IF EXISTS balance_stmt_view");
        st.execute("DROP VIEW IF EXISTS income_stmt_view");
    }

    private void dropLegacyPrototypeTransactionsIfNeeded(Connection conn, Statement st) throws SQLException {
        if (tableExists(conn, "TRANSACTIONS") && !columnExists(conn, "TRANSACTIONS", "DESCRIPTION")) {
            // The earlier prototype stored one spreadsheet row in TRANSACTIONS.
            // This first real-schema pass intentionally promotes TRANSACTIONS to
            // the accounting transaction header table.
            st.execute("DROP TABLE transactions");
        }
    }

    private boolean tableExists(Connection conn, String tableName) throws SQLException {
        try (ResultSet rs = conn.getMetaData().getTables(null, null, tableName, null)) {
            return rs.next();
        }
    }

    private boolean columnExists(Connection conn, String tableName, String columnName) throws SQLException {
        try (ResultSet rs = conn.getMetaData().getColumns(null, null, tableName, columnName)) {
            return rs.next();
        }
    }

    private void createAccountingCore(Statement st) throws SQLException {
        st.execute("""
            CREATE TABLE IF NOT EXISTS accounts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code VARCHAR(80),
                name VARCHAR(255) NOT NULL,
                account_type VARCHAR(40) NOT NULL,
                normal_balance VARCHAR(10) NOT NULL,
                report_section VARCHAR(120),
                active BOOLEAN NOT NULL DEFAULT TRUE,
                sort_order INT NOT NULL DEFAULT 0,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(name)
            )
            """);

        st.execute("""
            CREATE TABLE IF NOT EXISTS funds (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                active BOOLEAN NOT NULL DEFAULT TRUE,
                sort_order INT NOT NULL DEFAULT 0,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(name)
            )
            """);

        st.execute("""
            CREATE TABLE IF NOT EXISTS budget_categories (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                category_type VARCHAR(40) NOT NULL DEFAULT 'UNSPECIFIED',
                active BOOLEAN NOT NULL DEFAULT TRUE,
                sort_order INT NOT NULL DEFAULT 0,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(name)
            )
            """);

        st.execute("""
            CREATE TABLE IF NOT EXISTS bank_accounts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                account_number_last4 VARCHAR(12),
                interest_bearing BOOLEAN NOT NULL DEFAULT FALSE,
                active BOOLEAN NOT NULL DEFAULT TRUE,
                sort_order INT NOT NULL DEFAULT 0,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(name)
            )
            """);

        st.execute("""
            CREATE TABLE IF NOT EXISTS people (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                legal_name VARCHAR(255) NOT NULL,
                sca_name VARCHAR(255),
                email VARCHAR(255),
                phone VARCHAR(80),
                notes CLOB,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """);

        st.execute("""
            CREATE TABLE IF NOT EXISTS transactions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                transaction_date DATE NOT NULL,
                posting_date DATE,
                description CLOB,
                reference_number VARCHAR(120),
                person_id BIGINT,
                bank_account_id BIGINT,
                affects_bank VARCHAR(30) NOT NULL DEFAULT 'NOW',
                affects_budget VARCHAR(30) NOT NULL DEFAULT 'NOW',
                workbook_source_sheet VARCHAR(80),
                workbook_source_row INT,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_transactions_person FOREIGN KEY (person_id) REFERENCES people(id),
                CONSTRAINT fk_transactions_bank_account FOREIGN KEY (bank_account_id) REFERENCES bank_accounts(id)
            )
            """);

        st.execute("""
            CREATE TABLE IF NOT EXISTS transaction_lines (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                transaction_id BIGINT NOT NULL,
                account_id BIGINT NOT NULL,
                fund_id BIGINT,
                budget_category_id BIGINT,
                debit_amount DECIMAL(19,2) NOT NULL DEFAULT 0,
                credit_amount DECIMAL(19,2) NOT NULL DEFAULT 0,
                memo CLOB,
                line_order INT NOT NULL DEFAULT 0,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_transaction_lines_transaction FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE,
                CONSTRAINT fk_transaction_lines_account FOREIGN KEY (account_id) REFERENCES accounts(id),
                CONSTRAINT fk_transaction_lines_fund FOREIGN KEY (fund_id) REFERENCES funds(id),
                CONSTRAINT fk_transaction_lines_budget_category FOREIGN KEY (budget_category_id) REFERENCES budget_categories(id),
                CONSTRAINT chk_transaction_lines_debit_credit CHECK (debit_amount >= 0 AND credit_amount >= 0 AND NOT (debit_amount > 0 AND credit_amount > 0))
            )
            """);

        st.execute("""
            CREATE TABLE IF NOT EXISTS documents (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                transaction_id BIGINT,
                file_name VARCHAR(255) NOT NULL,
                content_type VARCHAR(120),
                storage_uri VARCHAR(500),
                notes CLOB,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_documents_transaction FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE SET NULL
            )
            """);
    }

    private void createWorkbookSupportTables(Statement st) throws SQLException {
        st.execute("""
            CREATE TABLE IF NOT EXISTS supplies (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                item_number VARCHAR(100),
                acquired_date DATE,
                description CLOB,
                item_count DECIMAL(19,2) NOT NULL DEFAULT 0,
                approximate_total_value DECIMAL(19,2) NOT NULL DEFAULT 0,
                value_per_item DECIMAL(19,2) NOT NULL DEFAULT 0,
                guardian_legal_name VARCHAR(255),
                guardian_email VARCHAR(255),
                guardian_phone VARCHAR(80),
                date_as_of DATE,
                last_confirmed DATE,
                returned_date DATE,
                notes CLOB,
                approved_by VARCHAR(255),
                removal_reason VARCHAR(255),
                number_removed DECIMAL(19,2) NOT NULL DEFAULT 0,
                additional_notes CLOB,
                active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """);

        st.execute("""
            CREATE TABLE IF NOT EXISTS inventory_items (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                transaction_line_id BIGINT,
                item_number VARCHAR(100),
                acquired_date DATE,
                description CLOB,
                item_count DECIMAL(19,2) NOT NULL DEFAULT 0,
                total_value DECIMAL(19,2) NOT NULL DEFAULT 0,
                item_type VARCHAR(255),
                used_for VARCHAR(255),
                guardian_name VARCHAR(255),
                confirmed_date DATE,
                notes CLOB,
                active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_inventory_transaction_line FOREIGN KEY (transaction_line_id) REFERENCES transaction_lines(id) ON DELETE SET NULL
            )
            """);

        st.execute("""
            CREATE TABLE IF NOT EXISTS bank_statement_lines (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                bank_account_id BIGINT,
                statement_date DATE,
                posted_date DATE,
                description CLOB,
                amount DECIMAL(19,2) NOT NULL DEFAULT 0,
                status VARCHAR(30) NOT NULL DEFAULT 'IMPORTED',
                matched_transaction_id BIGINT,
                notes CLOB,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_bank_statement_lines_account FOREIGN KEY (bank_account_id) REFERENCES bank_accounts(id),
                CONSTRAINT fk_bank_statement_lines_transaction FOREIGN KEY (matched_transaction_id) REFERENCES transactions(id) ON DELETE SET NULL
            )
            """);

        st.execute("""
            CREATE TABLE IF NOT EXISTS supplemental_lines (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                transaction_line_id BIGINT,
                line_kind VARCHAR(40) NOT NULL,
                counterparty_person_id BIGINT,
                description CLOB,
                reference VARCHAR(100),
                amount DECIMAL(19,2) NOT NULL DEFAULT 0,
                due_date DATE,
                start_date DATE,
                end_date DATE,
                remaining_amount DECIMAL(19,2) NOT NULL DEFAULT 0,
                notes CLOB,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_supplemental_transaction_line FOREIGN KEY (transaction_line_id) REFERENCES transaction_lines(id) ON DELETE SET NULL,
                CONSTRAINT fk_supplemental_counterparty FOREIGN KEY (counterparty_person_id) REFERENCES people(id)
            )
            """);

        st.execute("""
            CREATE TABLE IF NOT EXISTS period_close_records (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                period_start DATE NOT NULL,
                period_end DATE NOT NULL,
                bank_reconciled BOOLEAN NOT NULL DEFAULT FALSE,
                schedules_reviewed BOOLEAN NOT NULL DEFAULT FALSE,
                reports_generated BOOLEAN NOT NULL DEFAULT FALSE,
                close_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
                notes CLOB,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """);

        st.execute("""
            CREATE TABLE IF NOT EXISTS workbook_navigation_links (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                workbook_sheet_name VARCHAR(80) NOT NULL,
                panel_id VARCHAR(80) NOT NULL,
                display_label VARCHAR(120) NOT NULL,
                group_name VARCHAR(80) NOT NULL,
                sort_order INT NOT NULL DEFAULT 0,
                UNIQUE(workbook_sheet_name, panel_id)
            )
            """);

        // Keep the earlier lookup table available for old screens while the UI is being refactored.
        st.execute("""
            CREATE TABLE IF NOT EXISTS lookup_values (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                lookup_type VARCHAR(80) NOT NULL,
                display_name VARCHAR(255) NOT NULL,
                active BOOLEAN NOT NULL DEFAULT TRUE,
                sort_order INT NOT NULL DEFAULT 0,
                UNIQUE(lookup_type, display_name)
            )
            """);
    }

    private void createSearchIndexes(Statement st) throws SQLException {
        st.execute("CREATE INDEX IF NOT EXISTS idx_accounts_type_name ON accounts(account_type, name)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_accounts_report_section ON accounts(report_section, sort_order)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_funds_name ON funds(name)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_budget_categories_name ON budget_categories(name)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_bank_accounts_name ON bank_accounts(name)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_people_legal_name ON people(legal_name)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(transaction_date)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_transactions_reference ON transactions(reference_number)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_transactions_person_date ON transactions(person_id, transaction_date)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_transactions_bank_date ON transactions(bank_account_id, transaction_date)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_lines_transaction ON transaction_lines(transaction_id)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_lines_account ON transaction_lines(account_id)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_lines_fund ON transaction_lines(fund_id)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_lines_budget_category ON transaction_lines(budget_category_id)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_lines_account_transaction ON transaction_lines(account_id, transaction_id)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_lines_fund_transaction ON transaction_lines(fund_id, transaction_id)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_lines_budget_transaction ON transaction_lines(budget_category_id, transaction_id)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_bank_statement_match ON bank_statement_lines(bank_account_id, status, posted_date)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_supplemental_kind_due ON supplemental_lines(line_kind, due_date)");
        st.execute("CREATE INDEX IF NOT EXISTS idx_supplies_active_description ON supplies(active, item_number)");
    }

    private void createReportViews(Statement st) throws SQLException {
        st.execute("""
            CREATE OR REPLACE VIEW ledger_search AS
            SELECT
                t.id AS transaction_id,
                l.id AS line_id,
                t.transaction_date,
                t.posting_date,
                t.reference_number,
                t.description,
                p.legal_name,
                ba.name AS bank_account_name,
                t.affects_bank,
                t.affects_budget,
                a.id AS account_id,
                a.code AS account_code,
                a.name AS account_name,
                a.account_type,
                a.report_section,
                f.id AS fund_id,
                f.name AS fund_name,
                bc.id AS budget_category_id,
                bc.name AS budget_category_name,
                l.debit_amount,
                l.credit_amount,
                (l.debit_amount - l.credit_amount) AS signed_amount,
                l.memo
            FROM transaction_lines l
            JOIN transactions t ON t.id = l.transaction_id
            JOIN accounts a ON a.id = l.account_id
            LEFT JOIN funds f ON f.id = l.fund_id
            LEFT JOIN budget_categories bc ON bc.id = l.budget_category_id
            LEFT JOIN people p ON p.id = t.person_id
            LEFT JOIN bank_accounts ba ON ba.id = t.bank_account_id
            """);

        st.execute("""
            CREATE OR REPLACE VIEW transactions_list_view AS
            SELECT * FROM ledger_search
            """);

        st.execute("""
            CREATE OR REPLACE VIEW all_checks_tfrs_view AS
            SELECT *
            FROM ledger_search
            WHERE bank_account_name IS NOT NULL
               OR reference_number IS NOT NULL
            """);

        st.execute("""
            CREATE OR REPLACE VIEW fund_transfers_view AS
            SELECT
                transaction_id,
                transaction_date,
                reference_number,
                description,
                fund_name,
                SUM(debit_amount - credit_amount) AS fund_effect
            FROM ledger_search
            WHERE fund_name IS NOT NULL
            GROUP BY transaction_id, transaction_date, reference_number, description, fund_name
            HAVING COUNT(DISTINCT fund_name) >= 1
            """);

        st.execute("""
            CREATE OR REPLACE VIEW balance_stmt_view AS
            SELECT
                report_section,
                account_code,
                account_name,
                SUM(debit_amount - credit_amount) AS ending_balance
            FROM ledger_search
            WHERE account_type IN ('ASSET', 'LIABILITY', 'EQUITY')
            GROUP BY report_section, account_code, account_name
            """);

        st.execute("""
            CREATE OR REPLACE VIEW income_stmt_view AS
            SELECT
                report_section,
                account_code,
                account_name,
                SUM(credit_amount - debit_amount) AS activity_amount
            FROM ledger_search
            WHERE account_type IN ('INCOME', 'EXPENSE')
            GROUP BY report_section, account_code, account_name
            """);
    }

    private void seedReferenceData(Statement st) throws SQLException {
        seedFund(st, "General Fund", 10);
        seedFund(st, "Restricted Fund", 20);

        seedBudgetCategory(st, "Administrative", "EXPENSE", 10);
        seedBudgetCategory(st, "Event Income", "INCOME", 20);
        seedBudgetCategory(st, "Food", "EXPENSE", 30);
        seedBudgetCategory(st, "Meeting Space", "EXPENSE", 40);
        seedBudgetCategory(st, "Winter Snowball Fight 2026", "EVENT", 50);
        seedBudgetCategory(st, "Donations", "INCOME", 60);
        seedBudgetCategory(st, "Equipment", "EXPENSE", 70);

        seedBankAccount(st, "Checking", false, 10);
        seedBankAccount(st, "Savings", true, 20);

        seedAccount(st, "I.a", "Undep. & non-interest cash", "ASSET", "DEBIT", "BalanceStmt", 10);
        seedAccount(st, "I.b", "Cash Earning Interest", "ASSET", "DEBIT", "BalanceStmt", 20);
        seedAccount(st, "I.c", "Receivables", "ASSET", "DEBIT", "BalanceStmt", 30);
        seedAccount(st, "I.d", "Inventory", "ASSET", "DEBIT", "BalanceStmt", 40);
        seedAccount(st, "I.e", "Regalia", "ASSET", "DEBIT", "BalanceStmt", 50);
        seedAccount(st, "I.f", "Purchased Property & Equipment", "ASSET", "DEBIT", "BalanceStmt", 60);
        seedAccount(st, "I.g", "Less Accum. Depreciation", "ASSET", "CREDIT", "BalanceStmt", 70);
        seedAccount(st, "I.h", "Prepaid Expenses", "ASSET", "DEBIT", "BalanceStmt", 80);
        seedAccount(st, "I.i", "Other Assets", "ASSET", "DEBIT", "BalanceStmt", 90);
        seedAccount(st, "II.a", "Newsletter Subs. Due", "LIABILITY", "CREDIT", "BalanceStmt", 110);
        seedAccount(st, "II.b", "Deferred Revenue", "LIABILITY", "CREDIT", "BalanceStmt", 120);
        seedAccount(st, "II.c", "Payables", "LIABILITY", "CREDIT", "BalanceStmt", 130);
        seedAccount(st, "II.d", "Other Liabilities", "LIABILITY", "CREDIT", "BalanceStmt", 140);
        seedAccount(st, "III", "Net Assets", "EQUITY", "CREDIT", "BalanceStmt", 150);

        seedAccount(st, "1a", "Fundraising: Non-medieval activities to earn income (car washes, bake sales, etc.)", "INCOME", "CREDIT", "IncomeStmt", 210);
        seedAccount(st, "2.0", "Direct Contributions/Donations", "INCOME", "CREDIT", "IncomeStmt", 220);
        seedAccount(st, "3a", "Activity Related: Medieval activities to earn income (events, demos, heraldry fees)", "INCOME", "CREDIT", "IncomeStmt", 230);
        seedAccount(st, "21b", "21b Occupancy - Activity Rel", "EXPENSE", "DEBIT", "IncomeStmt", 310);

        seedLookup(st, "BANK_ACCOUNT", "Checking", 10);
        seedLookup(st, "BANK_ACCOUNT", "Savings", 20);
        seedLookup(st, "FUND", "General Fund", 10);
        seedLookup(st, "FUND", "Restricted Fund", 20);
        seedLookup(st, "BUDGET_CATEGORY", "Administrative", 10);
        seedLookup(st, "BUDGET_CATEGORY", "Event Income", 20);
        seedLookup(st, "BUDGET_CATEGORY", "Food", 30);
        seedLookup(st, "BUDGET_CATEGORY", "Meeting Space", 40);
        seedLookup(st, "BUDGET_CATEGORY", "Winter Snowball Fight 2026", 50);
        seedLookup(st, "BUDGET_CATEGORY", "Donations", 60);
        seedLookup(st, "BUDGET_CATEGORY", "Equipment", 70);

        seedNavigationLink(st, "WorkbookSummary", "WORKBOOK_SUMMARY", "Workbook Summary", "Workbook Pages", 10);
        seedNavigationLink(st, "WorkbookTables", "WORKBOOK_TABLES", "Workbook Tables", "Workbook Pages", 20);
        seedNavigationLink(st, "Supplies", "SUPPLIES", "Supplies", "Workbook Pages", 30);
        seedNavigationLink(st, "TransactionsList", "TRANSACTIONS_LIST", "Transactions List", "Workbook Pages", 40);
        seedNavigationLink(st, "AllChecksTfrs", "ALL_CHECKS_TFRS", "All Checks & Transfers", "Workbook Pages", 50);
        seedNavigationLink(st, "FundTransfers", "FUND_TRANSFERS", "Fund Transfers", "Workbook Pages", 60);
        seedNavigationLink(st, "BalanceStmt", "BALANCE_STMT", "Balance Statement", "Reports", 70);
        seedNavigationLink(st, "IncomeStmt", "INCOME_STMT", "Income Statement", "Reports", 80);
    }

    private void seedAccount(Statement st, String code, String name, String type, String normalBalance, String reportSection, int sortOrder) throws SQLException {
        st.executeUpdate("""
            MERGE INTO accounts (code, name, account_type, normal_balance, report_section, active, sort_order)
            KEY (name)
            VALUES ('%s', '%s', '%s', '%s', '%s', TRUE, %d)
            """.formatted(sql(code), sql(name), sql(type), sql(normalBalance), sql(reportSection), sortOrder));
    }

    private void seedFund(Statement st, String name, int sortOrder) throws SQLException {
        st.executeUpdate("""
            MERGE INTO funds (name, active, sort_order)
            KEY (name)
            VALUES ('%s', TRUE, %d)
            """.formatted(sql(name), sortOrder));
    }

    private void seedBudgetCategory(Statement st, String name, String type, int sortOrder) throws SQLException {
        st.executeUpdate("""
            MERGE INTO budget_categories (name, category_type, active, sort_order)
            KEY (name)
            VALUES ('%s', '%s', TRUE, %d)
            """.formatted(sql(name), sql(type), sortOrder));
    }

    private void seedBankAccount(Statement st, String name, boolean interestBearing, int sortOrder) throws SQLException {
        st.executeUpdate("""
            MERGE INTO bank_accounts (name, interest_bearing, active, sort_order)
            KEY (name)
            VALUES ('%s', %s, TRUE, %d)
            """.formatted(sql(name), interestBearing ? "TRUE" : "FALSE", sortOrder));
    }

    private void seedLookup(Statement st, String type, String name, int order) throws SQLException {
        st.executeUpdate("""
            MERGE INTO lookup_values (lookup_type, display_name, active, sort_order)
            KEY (lookup_type, display_name)
            VALUES ('%s', '%s', TRUE, %d)
            """.formatted(sql(type), sql(name), order));
    }

    private void seedNavigationLink(Statement st, String sheet, String panelId, String label, String group, int order) throws SQLException {
        st.executeUpdate("""
            MERGE INTO workbook_navigation_links (workbook_sheet_name, panel_id, display_label, group_name, sort_order)
            KEY (workbook_sheet_name, panel_id)
            VALUES ('%s', '%s', '%s', '%s', %d)
            """.formatted(sql(sheet), sql(panelId), sql(label), sql(group), order));
    }

    private String sql(String value) {
        return value == null ? "" : value.replace("'", "''");
    }
}
