package org.example.npbk.ui;

import java.math.BigDecimal; import java.time.LocalDate;
import org.example.npbk.model.*; import org.example.npbk.repo.LookupRepository; import org.example.npbk.service.InventoryService;
import javafx.collections.*; import javafx.geometry.Insets; import javafx.scene.Node; import javafx.scene.control.*; import javafx.scene.control.cell.ComboBoxTableCell; import javafx.scene.layout.*;

public class InventoryView {
    private final BorderPane root=new BorderPane(); private final TableView<InventoryItemViewModel> table=new TableView<>(); private final ObservableList<InventoryItemViewModel> rows=FXCollections.observableArrayList(); private final TextArea validationArea=new TextArea(); private final Label status=new Label("Ready.");
    private final LookupRepository lookups; private final InventoryService service;
    public InventoryView(LookupRepository lookups, InventoryService service){ this.lookups=lookups; this.service=service; build(); load(); }
    public Node getRoot(){return root;}
    private void build(){ table.setEditable(true); table.getSelectionModel().setCellSelectionEnabled(true); table.setItems(rows);
        table.getColumns().add(SpreadsheetUi.rowNumberColumn(table)); table.getColumns().add(text("Item #","item",90)); table.getColumns().add(date("Acquired", "acq", 115)); table.getColumns().add(text("Description","desc",260)); table.getColumns().add(money("Qty","qty",90)); table.getColumns().add(money("Total Value","value",115)); table.getColumns().add(comboString("Item Type", lookups.itemTypes(), 130)); table.getColumns().add(text("Used For","used",150)); table.getColumns().add(text("Guardian","guardian",160)); table.getColumns().add(date("Confirmed", "confirmed", 115)); table.getColumns().add(text("Notes","notes",220)); table.getColumns().add(stateCol());
        table.getSelectionModel().selectedItemProperty().addListener((o,old,row)->show(row)); SpreadsheetUi.installNavigation(table);
        Button add=new Button("Add Item"); add.setOnAction(e->addRow()); Button save=new Button("Save Selected"); save.setOnAction(e->saveSelected()); Button saveAll=new Button("Save All"); saveAll.setOnAction(e->saveAll());
        HBox toolbar=new HBox(8,add,save,saveAll,status); toolbar.setPadding(new Insets(8)); validationArea.setEditable(false); validationArea.setPrefRowCount(5); VBox bottom=new VBox(4,new Label("Validation"),validationArea); bottom.setPadding(new Insets(8)); root.setTop(toolbar); root.setCenter(table); root.setBottom(bottom); }
    private TableColumn<InventoryItemViewModel,String> text(String title,String prop,int width){ TableColumn<InventoryItemViewModel,String> c=new TableColumn<>(title); c.setCellValueFactory(v->switch(prop){case "item"->v.getValue().itemNumberProperty(); case "desc"->v.getValue().descriptionProperty(); case "used"->v.getValue().usedForProperty(); case "guardian"->v.getValue().guardianNameProperty(); default->v.getValue().notesProperty();}); c.setCellFactory(v->EditingCells.textCell()); c.setOnEditCommit(e->{ switch(prop){case "item"->e.getRowValue().setItemNumber(e.getNewValue()); case "desc"->e.getRowValue().setDescription(e.getNewValue()); case "used"->e.getRowValue().setUsedFor(e.getNewValue()); case "guardian"->e.getRowValue().setGuardianName(e.getNewValue()); default->e.getRowValue().setNotes(e.getNewValue());} after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<InventoryItemViewModel,LocalDate> date(String title,String prop,int width){ TableColumn<InventoryItemViewModel,LocalDate> c=new TableColumn<>(title); c.setCellValueFactory(v->prop.equals("acq")?v.getValue().acquiredDateProperty():v.getValue().confirmedDateProperty()); c.setCellFactory(v->EditingCells.dateCell()); c.setOnEditCommit(e->{ if(prop.equals("acq")) e.getRowValue().setAcquiredDate(e.getNewValue()); else e.getRowValue().setConfirmedDate(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<InventoryItemViewModel,BigDecimal> money(String title,String prop,int width){ TableColumn<InventoryItemViewModel,BigDecimal> c=new TableColumn<>(title); c.setCellValueFactory(v->prop.equals("qty")?v.getValue().quantityProperty():v.getValue().totalValueProperty()); c.setCellFactory(v->EditingCells.moneyCell()); c.setOnEditCommit(e->{ if(prop.equals("qty")) e.getRowValue().setQuantity(e.getNewValue()); else e.getRowValue().setTotalValue(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<InventoryItemViewModel,String> comboString(String title,ObservableList<String> choices,int width){ TableColumn<InventoryItemViewModel,String> c=new TableColumn<>(title); c.setCellValueFactory(v->v.getValue().itemTypeProperty()); c.setCellFactory(ComboBoxTableCell.forTableColumn(choices)); c.setOnEditCommit(e->{e.getRowValue().setItemType(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<InventoryItemViewModel,ValidationState> stateCol(){ TableColumn<InventoryItemViewModel,ValidationState> c=new TableColumn<>("State"); c.setCellValueFactory(v->v.getValue().validationStateProperty()); c.setEditable(false); c.setPrefWidth(90); return c; }
    private void after(InventoryItemViewModel r){ service.validate(r); table.refresh(); show(r); }
    private void load(){ rows.setAll(service.load()); if(rows.isEmpty()) addRow(); }
    private void addRow(){ InventoryItemViewModel r=new InventoryItemViewModel(); rows.add(r); table.getSelectionModel().clearAndSelect(rows.size()-1, table.getColumns().get(1)); }
    private void saveSelected(){ var r=table.getSelectionModel().getSelectedItem(); if(r==null)return; service.save(r); table.refresh(); show(r); status.setText("Inventory item saved."); }
    private void saveAll(){ service.saveAll(rows); table.refresh(); status.setText("Saved " + rows.size() + " inventory item(s)."); }
    private void show(InventoryItemViewModel r){ validationArea.setText(r==null?"":(r.getValidationMessages().isEmpty()?"No validation issues.":String.join("\n",r.getValidationMessages()))); }
}
