package org.example.npbk.ui;

import java.time.LocalDate;
import org.example.npbk.model.*; import org.example.npbk.service.PeriodCloseService;
import javafx.collections.*; import javafx.geometry.Insets; import javafx.scene.Node; import javafx.scene.control.*; import javafx.scene.control.cell.CheckBoxTableCell; import javafx.scene.control.cell.ComboBoxTableCell; import javafx.scene.layout.*;

public class PeriodCloseView {
    private final BorderPane root=new BorderPane(); private final TableView<PeriodCloseViewModel> table=new TableView<>(); private final ObservableList<PeriodCloseViewModel> rows=FXCollections.observableArrayList(); private final TextArea validationArea=new TextArea(); private final Label status=new Label("Ready."); private final PeriodCloseService service;
    public PeriodCloseView(PeriodCloseService service){ this.service=service; build(); load(); }
    public Node getRoot(){return root;}
    private void build(){ table.setEditable(true); table.getSelectionModel().setCellSelectionEnabled(true); table.setItems(rows);
        table.getColumns().add(SpreadsheetUi.rowNumberColumn(table)); table.getColumns().add(date("Period Start","start",120)); table.getColumns().add(date("Period End","end",120)); table.getColumns().add(bool("Bank Reconciled","bank",140)); table.getColumns().add(bool("Schedules Reviewed","sched",165)); table.getColumns().add(bool("Reports Generated","reports",160)); table.getColumns().add(statusCol()); table.getColumns().add(text("Notes",260)); table.getColumns().add(stateCol());
        table.getSelectionModel().selectedItemProperty().addListener((o,old,row)->show(row)); SpreadsheetUi.installNavigation(table);
        Label banner=new Label("First-pass period close checklist: validate ledger, outstanding items, supplemental schedules, and close-readiness flags. Later this becomes the controlled period-lock workflow.");
        Button add=new Button("Add Close Record"); add.setOnAction(e->addRow()); Button preview=new Button("Preview/Validate"); preview.setOnAction(e->preview()); Button save=new Button("Save Selected"); save.setOnAction(e->saveSelected()); Button saveAll=new Button("Save All"); saveAll.setOnAction(e->saveAll());
        HBox toolbar=new HBox(8,add,preview,save,saveAll,status); toolbar.setPadding(new Insets(8)); VBox top=new VBox(4,banner,toolbar); top.setPadding(new Insets(8)); validationArea.setEditable(false); validationArea.setPrefRowCount(7); VBox bottom=new VBox(4,new Label("Validation / Close Checklist"),validationArea); bottom.setPadding(new Insets(8)); root.setTop(top); root.setCenter(table); root.setBottom(bottom); }
    private TableColumn<PeriodCloseViewModel,LocalDate> date(String title,String prop,int width){ TableColumn<PeriodCloseViewModel,LocalDate> c=new TableColumn<>(title); c.setCellValueFactory(v->prop.equals("start")?v.getValue().periodStartProperty():v.getValue().periodEndProperty()); c.setCellFactory(v->EditingCells.dateCell()); c.setOnEditCommit(e->{ if(prop.equals("start")) e.getRowValue().setPeriodStart(e.getNewValue()); else e.getRowValue().setPeriodEnd(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<PeriodCloseViewModel,Boolean> bool(String title,String prop,int width){ TableColumn<PeriodCloseViewModel,Boolean> c=new TableColumn<>(title); c.setCellValueFactory(v->switch(prop){case "bank"->v.getValue().bankReconciledProperty(); case "sched"->v.getValue().schedulesReviewedProperty(); default->v.getValue().reportsGeneratedProperty();}); c.setCellFactory(CheckBoxTableCell.forTableColumn(c)); c.setOnEditCommit(e->{ if(prop.equals("bank")) e.getRowValue().setBankReconciled(e.getNewValue()); else if(prop.equals("sched")) e.getRowValue().setSchedulesReviewed(e.getNewValue()); else e.getRowValue().setReportsGenerated(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<PeriodCloseViewModel,PeriodCloseStatus> statusCol(){ TableColumn<PeriodCloseViewModel,PeriodCloseStatus> c=new TableColumn<>("Close Status"); c.setCellValueFactory(v->v.getValue().closeStatusProperty()); c.setCellFactory(ComboBoxTableCell.forTableColumn(FXCollections.observableArrayList(PeriodCloseStatus.values()))); c.setOnEditCommit(e->{e.getRowValue().setCloseStatus(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(140); return c; }
    private TableColumn<PeriodCloseViewModel,String> text(String title,int width){ TableColumn<PeriodCloseViewModel,String> c=new TableColumn<>(title); c.setCellValueFactory(v->v.getValue().notesProperty()); c.setCellFactory(v->EditingCells.textCell()); c.setOnEditCommit(e->{e.getRowValue().setNotes(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<PeriodCloseViewModel,ValidationState> stateCol(){ TableColumn<PeriodCloseViewModel,ValidationState> c=new TableColumn<>("State"); c.setCellValueFactory(v->v.getValue().validationStateProperty()); c.setEditable(false); c.setPrefWidth(90); return c; }
    private void after(PeriodCloseViewModel r){ service.validate(r); table.refresh(); show(r); }
    private void load(){ rows.setAll(service.load()); if(rows.isEmpty()) addRow(); }
    private void addRow(){ PeriodCloseViewModel r=new PeriodCloseViewModel(); r.setPeriodStart(LocalDate.now().withDayOfYear(1)); r.setPeriodEnd(LocalDate.now()); rows.add(r); table.getSelectionModel().clearAndSelect(rows.size()-1, table.getColumns().get(1)); }
    private void preview(){ var r=table.getSelectionModel().getSelectedItem(); if(r==null)return; service.validate(r); table.refresh(); show(r); status.setText("Close checklist refreshed."); }
    private void saveSelected(){ var r=table.getSelectionModel().getSelectedItem(); if(r==null)return; service.save(r); table.refresh(); show(r); status.setText("Close record saved."); }
    private void saveAll(){ service.saveAll(rows); table.refresh(); status.setText("Saved " + rows.size() + " close record(s)."); }
    private void show(PeriodCloseViewModel r){ validationArea.setText(r==null?"":(r.getValidationMessages().isEmpty()?"No validation issues.":String.join("\n",r.getValidationMessages()))); }
}
