package org.example.npbk.ui;

import java.math.BigDecimal; import java.time.LocalDate;
import org.example.npbk.model.*; import org.example.npbk.repo.LookupRepository; import org.example.npbk.service.BankingService;
import javafx.collections.*; import javafx.geometry.Insets; import javafx.scene.Node; import javafx.scene.control.*; import javafx.scene.control.cell.ComboBoxTableCell; import javafx.scene.layout.*;

public class BankingView {
    private final BorderPane root=new BorderPane(); private final TableView<BankStatementLineViewModel> table=new TableView<>(); private final ObservableList<BankStatementLineViewModel> rows=FXCollections.observableArrayList(); private final TextArea validationArea=new TextArea(); private final Label status=new Label("Ready.");
    private final LookupRepository lookups; private final BankingService service;
    public BankingView(LookupRepository lookups, BankingService service){ this.lookups=lookups; this.service=service; build(); load(); }
    public Node getRoot(){ return root; }
    private void build(){ table.setEditable(true); table.getSelectionModel().setCellSelectionEnabled(true); table.setItems(rows);
        table.getColumns().add(SpreadsheetUi.rowNumberColumn(table)); table.getColumns().add(comboString()); table.getColumns().add(date("Statement Date","statement",125)); table.getColumns().add(date("Posted Date","posted",125)); table.getColumns().add(text("Description","description",280)); table.getColumns().add(money("Amount",120)); table.getColumns().add(statusCol()); table.getColumns().add(longCol()); table.getColumns().add(text("Notes","notes",240)); table.getColumns().add(stateCol());
        table.getSelectionModel().selectedItemProperty().addListener((o,old,row)->show(row)); SpreadsheetUi.installNavigation(table);
        Label banner = new Label("First-pass banking grid: enter/import statement lines, match them to transaction ids, and mark reconciled. Later this becomes the statement-import and matching workflow.");
        Button add=new Button("Add Statement Line"); add.setOnAction(e->addRow()); Button save=new Button("Save Selected"); save.setOnAction(e->saveSelected()); Button saveAll=new Button("Save All"); saveAll.setOnAction(e->saveAll());
        HBox toolbar=new HBox(8,add,save,saveAll,status); toolbar.setPadding(new Insets(8)); VBox top=new VBox(4,banner,toolbar); top.setPadding(new Insets(8)); validationArea.setEditable(false); validationArea.setPrefRowCount(5); VBox bottom=new VBox(4,new Label("Validation"),validationArea); bottom.setPadding(new Insets(8)); root.setTop(top); root.setCenter(table); root.setBottom(bottom); }
    private TableColumn<BankStatementLineViewModel,String> comboString(){ TableColumn<BankStatementLineViewModel,String> c=new TableColumn<>("Bank Account"); c.setCellValueFactory(v->v.getValue().bankAccountProperty()); c.setCellFactory(ComboBoxTableCell.forTableColumn(lookups.bankAccounts())); c.setOnEditCommit(e->{e.getRowValue().setBankAccount(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(130); return c; }
    private TableColumn<BankStatementLineViewModel,LocalDate> date(String title,String prop,int width){ TableColumn<BankStatementLineViewModel,LocalDate> c=new TableColumn<>(title); c.setCellValueFactory(v->prop.equals("statement")?v.getValue().statementDateProperty():v.getValue().postedDateProperty()); c.setCellFactory(v->EditingCells.dateCell()); c.setOnEditCommit(e->{ if(prop.equals("statement")) e.getRowValue().setStatementDate(e.getNewValue()); else e.getRowValue().setPostedDate(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<BankStatementLineViewModel,String> text(String title,String prop,int width){ TableColumn<BankStatementLineViewModel,String> c=new TableColumn<>(title); c.setCellValueFactory(v->prop.equals("description")?v.getValue().descriptionProperty():v.getValue().notesProperty()); c.setCellFactory(v->EditingCells.textCell()); c.setOnEditCommit(e->{ if(prop.equals("description")) e.getRowValue().setDescription(e.getNewValue()); else e.getRowValue().setNotes(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<BankStatementLineViewModel,BigDecimal> money(String title,int width){ TableColumn<BankStatementLineViewModel,BigDecimal> c=new TableColumn<>(title); c.setCellValueFactory(v->v.getValue().amountProperty()); c.setCellFactory(v->EditingCells.moneyCell()); c.setOnEditCommit(e->{e.getRowValue().setAmount(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<BankStatementLineViewModel,BankStatementLineStatus> statusCol(){ TableColumn<BankStatementLineViewModel,BankStatementLineStatus> c=new TableColumn<>("Status"); c.setCellValueFactory(v->v.getValue().statusProperty()); c.setCellFactory(ComboBoxTableCell.forTableColumn(FXCollections.observableArrayList(BankStatementLineStatus.values()))); c.setOnEditCommit(e->{e.getRowValue().setStatus(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(115); return c; }
    private TableColumn<BankStatementLineViewModel,Long> longCol(){ TableColumn<BankStatementLineViewModel,Long> c=new TableColumn<>("Matched Txn Id"); c.setCellValueFactory(v->v.getValue().matchedTransactionIdProperty()); c.setCellFactory(v->EditingCells.longCell()); c.setOnEditCommit(e->{e.getRowValue().setMatchedTransactionId(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(120); return c; }
    private TableColumn<BankStatementLineViewModel,ValidationState> stateCol(){ TableColumn<BankStatementLineViewModel,ValidationState> c=new TableColumn<>("State"); c.setCellValueFactory(v->v.getValue().validationStateProperty()); c.setEditable(false); c.setPrefWidth(90); return c; }
    private void after(BankStatementLineViewModel r){ service.validate(r); table.refresh(); show(r); }
    private void load(){ rows.setAll(service.load()); if(rows.isEmpty()) addRow(); }
    private void addRow(){ BankStatementLineViewModel r=new BankStatementLineViewModel(); rows.add(r); table.getSelectionModel().clearAndSelect(rows.size()-1, table.getColumns().get(1)); }
    private void saveSelected(){ var r=table.getSelectionModel().getSelectedItem(); if(r==null)return; service.save(r); table.refresh(); show(r); status.setText("Bank statement line saved."); }
    private void saveAll(){ service.saveAll(rows); table.refresh(); status.setText("Saved " + rows.size() + " bank line(s)."); }
    private void show(BankStatementLineViewModel r){ validationArea.setText(r==null?"":(r.getValidationMessages().isEmpty()?"No validation issues.":String.join("\n",r.getValidationMessages()))); }
}
