package org.example.npbk.ui;

import java.math.BigDecimal; import java.time.LocalDate;
import org.example.npbk.model.*; import org.example.npbk.repo.LookupRepository; import org.example.npbk.service.OutstandingService;
import javafx.collections.*; import javafx.geometry.Insets; import javafx.scene.Node; import javafx.scene.control.*; import javafx.scene.control.cell.ComboBoxTableCell; import javafx.scene.layout.*;

public class OutstandingView {
    private final BorderPane root=new BorderPane(); private final TableView<OutstandingItemViewModel> table=new TableView<>(); private final ObservableList<OutstandingItemViewModel> rows=FXCollections.observableArrayList(); private final TextArea validationArea=new TextArea(); private final Label status=new Label("Ready.");
    private final LookupRepository lookups; private final OutstandingService service;
    public OutstandingView(LookupRepository lookups, OutstandingService service){ this.lookups=lookups; this.service=service; build(); load(); }
    public Node getRoot(){ return root; }
    private void build(){ table.setEditable(true); table.getSelectionModel().setCellSelectionEnabled(true); table.setItems(rows);
        table.getColumns().add(SpreadsheetUi.rowNumberColumn(table)); table.getColumns().add(longCol("Txn Id", "source", 80)); table.getColumns().add(dateCol("Date Sent/Received", "date", 145)); table.getColumns().add(text("Ref #", "ref", 90)); table.getColumns().add(text("Name", "name", 180)); table.getColumns().add(text("Details", "details", 240)); table.getColumns().add(comboString("Bank Account", lookups.bankAccounts(), 130)); table.getColumns().add(directionCol()); table.getColumns().add(money("Amount", 110)); table.getColumns().add(dateCol("Date Cleared", "cleared", 125)); table.getColumns().add(statusCol()); table.getColumns().add(text("Notes", "notes", 220)); table.getColumns().add(stateCol());
        table.getSelectionModel().selectedItemProperty().addListener((o,old,row)->show(row)); SpreadsheetUi.installNavigation(table);
        Button add=new Button("Add Item"); add.setOnAction(e->addRow()); Button save=new Button("Save Selected"); save.setOnAction(e->saveSelected()); Button saveAll=new Button("Save All"); saveAll.setOnAction(e->saveAll()); Button recalc=new Button("Recalculate"); recalc.setOnAction(e->recalcAll());
        HBox toolbar=new HBox(8,add,save,saveAll,recalc,status); toolbar.setPadding(new Insets(8)); validationArea.setEditable(false); validationArea.setPrefRowCount(5); VBox bottom=new VBox(4,new Label("Validation"),validationArea); bottom.setPadding(new Insets(8)); root.setTop(toolbar); root.setCenter(table); root.setBottom(bottom); }
    private TableColumn<OutstandingItemViewModel,Long> longCol(String title,String prop,int width){ TableColumn<OutstandingItemViewModel,Long> c=new TableColumn<>(title); c.setCellValueFactory(v->v.getValue().sourceTransactionIdProperty()); c.setCellFactory(v->EditingCells.longCell()); c.setOnEditCommit(e->{e.getRowValue().setSourceTransactionId(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<OutstandingItemViewModel,LocalDate> dateCol(String title,String prop,int width){ TableColumn<OutstandingItemViewModel,LocalDate> c=new TableColumn<>(title); c.setCellValueFactory(v->prop.equals("date")?v.getValue().dateIssuedProperty():v.getValue().clearedDateProperty()); c.setCellFactory(v->EditingCells.dateCell()); c.setOnEditCommit(e->{ if(prop.equals("date")) e.getRowValue().setDateIssued(e.getNewValue()); else e.getRowValue().setClearedDate(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<OutstandingItemViewModel,String> text(String title,String prop,int width){ TableColumn<OutstandingItemViewModel,String> c=new TableColumn<>(title); c.setCellValueFactory(v->switch(prop){case "ref"->v.getValue().referenceNumberProperty(); case "name"->v.getValue().nameProperty(); case "details"->v.getValue().detailsProperty(); default->v.getValue().notesProperty();}); c.setCellFactory(v->EditingCells.textCell()); c.setOnEditCommit(e->{ switch(prop){case "ref"->e.getRowValue().setReferenceNumber(e.getNewValue()); case "name"->e.getRowValue().setName(e.getNewValue()); case "details"->e.getRowValue().setDetails(e.getNewValue()); default->e.getRowValue().setNotes(e.getNewValue());} after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<OutstandingItemViewModel,String> comboString(String title,ObservableList<String> choices,int width){ TableColumn<OutstandingItemViewModel,String> c=new TableColumn<>(title); c.setCellValueFactory(v->v.getValue().bankAccountProperty()); c.setCellFactory(ComboBoxTableCell.forTableColumn(choices)); c.setOnEditCommit(e->{e.getRowValue().setBankAccount(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<OutstandingItemViewModel,OutstandingDirection> directionCol(){ TableColumn<OutstandingItemViewModel,OutstandingDirection> c=new TableColumn<>("Direction"); c.setCellValueFactory(v->v.getValue().directionProperty()); c.setCellFactory(ComboBoxTableCell.forTableColumn(FXCollections.observableArrayList(OutstandingDirection.values()))); c.setOnEditCommit(e->{e.getRowValue().setDirection(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(160); return c; }
    private TableColumn<OutstandingItemViewModel,OutstandingStatus> statusCol(){ TableColumn<OutstandingItemViewModel,OutstandingStatus> c=new TableColumn<>("Status"); c.setCellValueFactory(v->v.getValue().statusProperty()); c.setCellFactory(ComboBoxTableCell.forTableColumn(FXCollections.observableArrayList(OutstandingStatus.values()))); c.setOnEditCommit(e->{e.getRowValue().setStatus(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(100); return c; }
    private TableColumn<OutstandingItemViewModel,BigDecimal> money(String title,int width){ TableColumn<OutstandingItemViewModel,BigDecimal> c=new TableColumn<>(title); c.setCellValueFactory(v->v.getValue().amountProperty()); c.setCellFactory(v->EditingCells.moneyCell()); c.setOnEditCommit(e->{e.getRowValue().setAmount(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<OutstandingItemViewModel,ValidationState> stateCol(){ TableColumn<OutstandingItemViewModel,ValidationState> c=new TableColumn<>("State"); c.setCellValueFactory(v->v.getValue().validationStateProperty()); c.setEditable(false); c.setPrefWidth(90); return c; }
    private void after(OutstandingItemViewModel r){ service.recalculate(r); service.validate(r); table.refresh(); show(r); }
    private void load(){ rows.setAll(service.load()); if(rows.isEmpty()) addRow(); }
    private void addRow(){ OutstandingItemViewModel r=new OutstandingItemViewModel(); rows.add(r); table.getSelectionModel().clearAndSelect(rows.size()-1, table.getColumns().get(1)); }
    private void saveSelected(){ var r=table.getSelectionModel().getSelectedItem(); if(r==null)return; service.save(r); table.refresh(); show(r); status.setText("Outstanding item saved."); }
    private void saveAll(){ service.saveAll(rows); table.refresh(); status.setText("Saved " + rows.size() + " outstanding item(s)."); }
    private void recalcAll(){ rows.forEach(r->{service.recalculate(r); service.validate(r);}); table.refresh(); status.setText("Recalculated outstanding items."); }
    private void show(OutstandingItemViewModel r){ validationArea.setText(r==null?"":(r.getValidationMessages().isEmpty()?"No validation issues.":String.join("\n",r.getValidationMessages()))); }
}
