package org.example.npbk.ui;

import java.math.BigDecimal; import java.time.LocalDate;
import org.example.npbk.model.*; import org.example.npbk.service.SupplementalLineService;
import javafx.collections.*; import javafx.geometry.Insets; import javafx.scene.Node; import javafx.scene.control.*; import javafx.scene.control.cell.ComboBoxTableCell; import javafx.scene.layout.*;

public class SupplementalLinesView {
    private final BorderPane root=new BorderPane(); private final TableView<SupplementalLineViewModel> table=new TableView<>(); private final ObservableList<SupplementalLineViewModel> rows=FXCollections.observableArrayList(); private final TextArea validationArea=new TextArea(); private final Label status=new Label("Ready.");
    private final SupplementalLineService service; private final boolean assetSide; private final ObservableList<SupplementalLineKind> allowedKinds;
    public SupplementalLinesView(String title, boolean assetSide, SupplementalLineService service){ this.assetSide=assetSide; this.service=service; this.allowedKinds=assetSide?FXCollections.observableArrayList(SupplementalLineKind.RECEIVABLE,SupplementalLineKind.PREPAID_EXPENSE,SupplementalLineKind.OTHER_ASSET):FXCollections.observableArrayList(SupplementalLineKind.DEFERRED_REVENUE,SupplementalLineKind.PAYABLE,SupplementalLineKind.OTHER_LIABILITY); build(title); load(); }
    public Node getRoot(){ return root; }
    private void build(String title){ table.setEditable(true); table.getSelectionModel().setCellSelectionEnabled(true); table.setItems(rows);
        table.getColumns().add(SpreadsheetUi.rowNumberColumn(table)); table.getColumns().add(kindCol()); table.getColumns().add(longCol()); table.getColumns().add(text("Counterparty","counterparty",170)); table.getColumns().add(text("Description","description",230)); table.getColumns().add(text("Reference","reference",110)); table.getColumns().add(money("Amount","amount",true,110)); table.getColumns().add(date("Due Date","due",110)); table.getColumns().add(date("Start Date","start",110)); table.getColumns().add(date("End Date","end",110)); table.getColumns().add(money("Remaining","remaining",false,110)); table.getColumns().add(text("Notes","notes",220)); table.getColumns().add(stateCol());
        table.getSelectionModel().selectedItemProperty().addListener((o,old,row)->show(row)); SpreadsheetUi.installNavigation(table);
        Button add=new Button("Add Line"); add.setOnAction(e->addRow()); Button save=new Button("Save Selected"); save.setOnAction(e->saveSelected()); Button saveAll=new Button("Save All"); saveAll.setOnAction(e->saveAll()); Button recalc=new Button("Recalculate"); recalc.setOnAction(e->recalcAll());
        HBox toolbar=new HBox(8,new Label(title),add,save,saveAll,recalc,status); toolbar.setPadding(new Insets(8)); validationArea.setEditable(false); validationArea.setPrefRowCount(5); VBox bottom=new VBox(4,new Label("Validation"),validationArea); bottom.setPadding(new Insets(8)); root.setTop(toolbar); root.setCenter(table); root.setBottom(bottom); }
    private TableColumn<SupplementalLineViewModel,SupplementalLineKind> kindCol(){ TableColumn<SupplementalLineViewModel,SupplementalLineKind> c=new TableColumn<>("Kind"); c.setCellValueFactory(v->v.getValue().lineKindProperty()); c.setCellFactory(ComboBoxTableCell.forTableColumn(allowedKinds)); c.setOnEditCommit(e->{e.getRowValue().setLineKind(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(150); return c; }
    private TableColumn<SupplementalLineViewModel,Long> longCol(){ TableColumn<SupplementalLineViewModel,Long> c=new TableColumn<>("Linked Txn Id"); c.setCellValueFactory(v->v.getValue().linkedTransactionIdProperty()); c.setCellFactory(v->EditingCells.longCell()); c.setOnEditCommit(e->{e.getRowValue().setLinkedTransactionId(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(110); return c; }
    private TableColumn<SupplementalLineViewModel,String> text(String title,String prop,int width){ TableColumn<SupplementalLineViewModel,String> c=new TableColumn<>(title); c.setCellValueFactory(v->switch(prop){case "counterparty"->v.getValue().counterpartyProperty(); case "description"->v.getValue().descriptionProperty(); case "reference"->v.getValue().referenceProperty(); default->v.getValue().notesProperty();}); c.setCellFactory(v->EditingCells.textCell()); c.setOnEditCommit(e->{ switch(prop){case "counterparty"->e.getRowValue().setCounterparty(e.getNewValue()); case "description"->e.getRowValue().setDescription(e.getNewValue()); case "reference"->e.getRowValue().setReference(e.getNewValue()); default->e.getRowValue().setNotes(e.getNewValue());} after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<SupplementalLineViewModel,LocalDate> date(String title,String prop,int width){ TableColumn<SupplementalLineViewModel,LocalDate> c=new TableColumn<>(title); c.setCellValueFactory(v->switch(prop){case "due"->v.getValue().dueDateProperty(); case "start"->v.getValue().startDateProperty(); default->v.getValue().endDateProperty();}); c.setCellFactory(v->EditingCells.dateCell()); c.setOnEditCommit(e->{ switch(prop){case "due"->e.getRowValue().setDueDate(e.getNewValue()); case "start"->e.getRowValue().setStartDate(e.getNewValue()); default->e.getRowValue().setEndDate(e.getNewValue());} after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<SupplementalLineViewModel,BigDecimal> money(String title,String prop,boolean edit,int width){ TableColumn<SupplementalLineViewModel,BigDecimal> c=new TableColumn<>(title); c.setCellValueFactory(v->prop.equals("amount")?v.getValue().amountProperty():v.getValue().remainingAmountProperty()); c.setCellFactory(v->EditingCells.moneyCell()); c.setEditable(edit); if(edit)c.setOnEditCommit(e->{e.getRowValue().setAmount(e.getNewValue()); after(e.getRowValue());}); c.setPrefWidth(width); return c; }
    private TableColumn<SupplementalLineViewModel,ValidationState> stateCol(){ TableColumn<SupplementalLineViewModel,ValidationState> c=new TableColumn<>("State"); c.setCellValueFactory(v->v.getValue().validationStateProperty()); c.setEditable(false); c.setPrefWidth(90); return c; }
    private void after(SupplementalLineViewModel r){ service.recalculate(r); service.validate(r); table.refresh(); show(r); }
    private void load(){ rows.setAll(assetSide?service.loadAssetLines():service.loadLiabilityLines()); if(rows.isEmpty()) addRow(); }
    private void addRow(){ SupplementalLineViewModel r=new SupplementalLineViewModel(); r.setLineKind(assetSide?SupplementalLineKind.RECEIVABLE:SupplementalLineKind.DEFERRED_REVENUE); rows.add(r); table.getSelectionModel().clearAndSelect(rows.size()-1, table.getColumns().get(1)); }
    private void saveSelected(){ var r=table.getSelectionModel().getSelectedItem(); if(r==null)return; service.save(r); table.refresh(); show(r); status.setText("Supplemental line saved."); }
    private void saveAll(){ service.saveAll(rows); table.refresh(); status.setText("Saved " + rows.size() + " supplemental line(s)."); }
    private void recalcAll(){ rows.forEach(r->{service.recalculate(r); service.validate(r);}); table.refresh(); status.setText("Recalculated supplemental lines."); }
    private void show(SupplementalLineViewModel r){ validationArea.setText(r==null?"":(r.getValidationMessages().isEmpty()?"No validation issues.":String.join("\n",r.getValidationMessages()))); }
}
